languageCode = "zh-tw"
contentDir = "content"
languageName = "æ­£é«”ä¸­æ–‡"
weight = 2
title = "Zakk"

[params]
  displayName = "æ­£é«”ä¸­æ–‡"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2006å¹´1æœˆ2æ—¥"
  logo = "img/logo-small.png"
  description = """
<div class=\"text-center\">
ğŸ©·ğŸ’›ğŸ©µ  ğŸ“ æ¾³å¤§åˆ©äº ğŸ‡¦ğŸ‡º<br/>
ğŸ•“ UTC +10 (AEST) â„ï¸<br/>
â¤ï¸ Paper âœ¨<br/>
ğŸ¹ å¤©ç«ºé¼  ğŸ¥”<br/>
ğŸ® éŠæˆ² Â· ğŸ§ Linux Â· ğŸ’¹ é‡‘è<br/>
ğŸ©·ğŸ’›ğŸ©µ
</div>
"""

[params.author]
  name = "Zakk"
  email = "admin@zakk.au"
  image = "https://avatars.githubusercontent.com/u/221879664?v=4"
  headline = """
<div class=\"text-center\">
ğŸ©·ğŸ’›ğŸ©µ  ğŸ“ æ¾³å¤§åˆ©äº ğŸ‡¦ğŸ‡º<br/>
ğŸ•“ UTC +10 (AEST) â„ï¸<br/>
â¤ï¸ Paper âœ¨<br/>
ğŸ¹ å¤©ç«ºé¼  ğŸ¥”<br/>
ğŸ® éŠæˆ² Â· ğŸ§ Linux Â· ğŸ’¹ é‡‘è<br/>
ğŸ©·ğŸ’›ğŸ©µ
</div>
"""
  bio = "åœ¨æ¾³æ´²å­¸ç¿’å•†ç§‘èˆ‡ Paper é è·é›¢æˆ€æ„›ï¼Œé¤Šè‘— é¦¬éˆ´è–¯ åŠ è„†è–¯é¤…ï¼Œæ’°å¯« Linux ç­†è¨˜èˆ‡ç”Ÿæ´»é›œè¨˜ã€‚"
  links = [
    { instagram = "https://www.instagram.com/zakk.au/" },
    { github = "https://github.com/Zakkaus" },
    { x-twitter = "https://x.com/zakkauu" },
    { email = "mailto:admin@zakk.au" }
  ]

