languageCode = "zh-tw"
languageName = "æ­£é«”ä¸­æ–‡"
weight = 2
title = "Zakk"

[params]
  displayName = "æ­£é«”ä¸­æ–‡"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2006å¹´1æœˆ2æ—¥"
  logo = "img/logo-small.png"
  description = "é›™èªåˆ†äº« Gentoo ç­†è¨˜ã€è¨­è¨ˆå¯¦é©—ã€èˆ‡ Paper çš„é è·ç”Ÿæ´»é‚„æœ‰å…©éš»å¤©ç«ºé¼ ã€‚"

[params.author]
  name = "Zakk"
  email = "admin@zakk.au"
  image = "https://avatars.githubusercontent.com/u/221879664?v=4"
  headline = """
ğŸ©·ğŸ’›ğŸ©µ  ğŸ“ æ¾³å¤§åˆ©äº ğŸ‡¦ğŸ‡º
ğŸ•“ UTC +10 (AEST) â„ï¸
â¤ï¸ Paper âœ¨
ğŸ¹ å¤©ç«ºé¼  ğŸ¥”
ğŸ® éŠæˆ² Â· ğŸ§ Linux Â· ğŸ’¹ é‡‘è
ğŸ©·ğŸ’›ğŸ©µ
"""
  bio = "èˆ‡ Paper é è·é›¢æˆ€æ„›ï¼Œé¤Šè‘— Potato åŠ Hash Brownï¼Œæ’°å¯« Gentoo ç­†è¨˜èˆ‡ç”Ÿæ´»é›œè¨˜ã€‚"
  links = [
    { instagram = "https://www.instagram.com/zakk.au/" },
    { github = "https://github.com/Zakkaus" },
    { x-twitter = "https://x.com/zakkauu" },
    { email = "mailto:admin@zakk.au" }
  ]

