languageCode = "zh-cn"
languageName = "ç®€ä½“ä¸­æ–‡"
weight = 3
title = "Zakk"

[params]
  displayName = "ç®€ä½“ä¸­æ–‡"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo-small.png"
  description = """
ğŸ©·ğŸ’›ğŸ©µ  ğŸ“ æ¾³å¤§åˆ©äºš ğŸ‡¦ğŸ‡º  
ğŸ•“ UTC +10 (AEST) â„ï¸  
â¤ï¸ Paper âœ¨  
ğŸ¹ å¤©ç«ºé¼  ğŸ¥”  
ğŸ® æ¸¸æˆ Â· ğŸ§ Linux Â· ğŸ’¹ é‡‘è  
ğŸ©·ğŸ’›ğŸ©µ
"""

[params.author]
  name = "Zakk"
  email = "admin@zakk.au"
  image = "https://avatars.githubusercontent.com/u/221879664?v=4"
  headline = """
ğŸ©·ğŸ’›ğŸ©µ  ğŸ“ æ¾³å¤§åˆ©äºš ğŸ‡¦ğŸ‡º
ğŸ•“ UTC +10 (AEST) â„ï¸
â¤ï¸ Paper âœ¨
ğŸ¹ å¤©ç«ºé¼  ğŸ¥”
ğŸ® æ¸¸æˆ Â· ğŸ§ Linux Â· ğŸ’¹ é‡‘è
ğŸ©·ğŸ’›ğŸ©µ
"""
  bio = "ä¸ Paper å¼‚åœ°æ‹ï¼Œå…»ç€ Potato ä¸ Hash Brownï¼Œä¸¤åªå¯çˆ±çš„å¤©ç«ºé¼ ï¼ŒåŒæ—¶å†™ Gentoo ä¸æ—¥å¸¸éšç¬”ã€‚"
  links = [
    { instagram = "https://www.instagram.com/zakk.au/" },
    { github = "https://github.com/Zakkaus" },
    { x-twitter = "https://x.com/zakkauu" },
    { email = "mailto:admin@zakk.au" },
  ]