languageCode = "en"
contentDir = "content"
languageName = "English"
weight = 1
title = "Zakk"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo-small.png"
  description = """
<div class=\"text-center\">
ğŸ“ Australia ğŸ‡¦ğŸ‡º<br/>
ğŸ•“ UTC +10 (AEST) â„ï¸<br/>
â¤ï¸ Paper âœ¨<br/>
ğŸ¹ Guinea pigs ğŸ¥”<br/>
ğŸ® Gaming Â· ğŸ§ Linux Â· ğŸ’¹ Finance<br/>
ğŸ©·ğŸ’›ğŸ©µ
</div>
"""

[params.author]
  name = "Zakk"
  email = "admin@zakk.au"
  image = "https://avatars.githubusercontent.com/u/221879664?v=4"
  headline = """
<div class=\"text-center\">
ğŸ“ Australia ğŸ‡¦ğŸ‡º<br/>
ğŸ•“ UTC +10 (AEST) â„ï¸<br/>
â¤ï¸ Paper âœ¨<br/>
ğŸ¹ Guinea pigs ğŸ¥”<br/>
ğŸ® Gaming Â· ğŸ§ Linux Â· ğŸ’¹ Finance<br/>
ğŸ©·ğŸ’›ğŸ©µ
</div>
"""
  bio = "Long-distance with Paper, raising Potato & Hash Brown, tinkering with Gentoo, and collecting cozy routines."
  links = [
    { instagram = "https://www.instagram.com/zakk.au/" },
    { github = "https://github.com/Zakkaus" },
    { x-twitter = "https://x.com/zakkauu" },
    { email = "mailto:admin@zakk.au" },
  ]